# Generated by Django 4.2.3 on 2023-07-17 05:41

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_perfilusuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='direccion',
            field=models.CharField(default='Valor predeterminado', max_length=100),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Usuario'),
        ),
    ]
